#if !defined(BBERROR_H)
#define BBERROR_H

#include <Arduino.h>

namespace bb {

typedef enum {
	ERROR_NOT_PRESENT = 0x00,
	ERROR_OK          = 0x01,
	ERROR_COMM        = 0x02,
	ERROR_FLAGS       = 0x0f,
	ERROR_VOLTAGE     = 0x10,
	ERROR_TEMP        = 0x20,
	ERROR_OVERLOAD    = 0x40,
	ERROR_OTHER       = 0x80
} ErrorState;

typedef enum {
	RES_OK = 0, // no error :-) 

	RES_PARAM_NO_SUCH_PARAMETER = 1,
	RES_PARAM_INVALID_TYPE = 2,
	RES_PARAM_INVALID_VALUE = 3,
	RES_PARAM_READONLY_PARAMETER = 4,

	RES_SUBSYS_HW_DEPENDENCY_MISSING = 5,
	RES_SUBSYS_HW_DEPENDENCY_LOCKED = 6,
	RES_SUBSYS_ALREADY_REGISTERED = 7,
	RES_SUBSYS_NO_SUCH_SUBSYS = 8,
	RES_SUBSYS_RESOURCE_NOT_AVAILABLE = 9,
	RES_SUBSYS_COMM_ERROR = 10,
	RES_SUBSYS_PROTOCOL_ERROR = 11,
	RES_SUBSYS_ALREADY_STARTED = 12,
	RES_SUBSYS_NOT_STARTED = 13,
	RES_SUBSYS_NOT_OPERATIONAL = 14,
	RES_SUBSYS_NOT_STOPPABLE = 15,
	RES_SUBSYS_NOT_INITIALIZED = 16,
	RES_SUBSYS_ALREADY_INITIALIZED = 17,
	RES_SUBSYS_WRONG_MODE = 18,

	RES_CONFIG_INVALID_HANDLE = 19,

	RES_COMM_TIMEOUT = 20,

	RES_CMD_UNKNOWN_COMMAND = 21,
	RES_CMD_INVALID_ARGUMENT_COUNT = 22,
	RES_CMD_INVALID_ARGUMENT = 23,
	RES_CMD_FAILURE = 24,

	RES_COMMON_NOT_IN_LIST = 25,
	RES_COMMON_DUPLICATE_IN_LIST = 26,
	RES_COMMON_OUT_OF_RANGE = 27,

	RES_PACKET_TOO_SHORT = 28,
	RES_PACKET_TOO_LONG = 29,
	RES_PACKET_INVALID_PACKET = 30,
	
	RES_DROID_VOLTAGE_TOO_LOW = 31,
	RES_DROID_VOLTAGE_TOO_HIGH = 32,
	RES_DROID_CURRENT_TOO_HIGH = 33,
	RES_DROID_WRONG_DIRECTION = 34
} Result;

const char* errorMessage(Result res);

};

#endif // BBERROR_H