static unsigned int QRCODE_WIDTH=80;
static unsigned int QRCODE_HEIGHT=80;
#define HEADER_PIXEL_GREYSCALE(data,pixel) { pixel = int((*data-32)*2.71); data++; }
static const char *QRCODE_DATA = 
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~[MMMMMMMMMMMMMMMMMMM`~~~~~oMMi~~iMMMMMr~~`MMw~~WMM|~}NMMMMMMMMMMMMMMMMMMMi~~~"
"~~~M                   T~~~~~k  b~~b     n~~T  u~~D  |~})                   b~~~"
"~~~M                   T~~~~~k  b~~b     o~~T  u~~D  |~})                   b~~~"
"~~~M  syyyyyyyyyyyyyp  T~~qDD<  b~~{yyZ  =DD3  u~~D  |~}) 6yyyyyyyyyyyyyyg  b~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~n     b~~~~~^        u~~D  |~}) 8~~~~~~~~~~~~~~k  b~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~n     b~~~~~^        u~~C  |~}) 8~~~~~~~~~~~~~~k  b~~~"
"~~~M  y~~A8888888J~~u  T~~n     b~~d88k||X     u~~|||~~}) 8~~y68888888]~~k  b~~~"
"~~~M  y~~8       D~~u  T~~n     b~~b  k~~Y     u~~~~~~~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~o)))))b}}b))k}}Z))#  u}}}}}~~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~~}}}}}g))g}}^))n}}T  ())))%|~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~g  g~~^  n~~T        |~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~h88g||]  l||W88888'  |~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~~~~b        r~~~~~D  |~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~~~~b        q~~~~~D  |~}) 8~~y        Y~~k  b~~~"
"~~~M  y~~JDDDDDDDQ~~u  T~~~~~|yy{~~gDDDDDDDDs~~zyyB  |~}) 8~~yCDDDDDDD`~~k  b~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~~~~k  b~~~~~~~~~~~~~~M     |~}) 8~~~~~~~~~~~~~~k  b~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~~~~k  b~~~~~~~~~~~~~~M     |~}) 8~~~~~~~~~~~~~~k  b~~~"
"~~~M  puuuuuuuuuuuuum  T~~{uuiMMduuz~~yuu{~~xuuXMM0  |~}) 5uuuuuuuuuuuuuud  b~~~"
"~~~M                   T~~n  ^~~g  g~~^  n~~T  u~~D  |~})                   b~~~"
"~~~M                   T~~n  ^~~g  g~~^  n~~T  u~~D  |~})                   b~~~"
"~~~`TTTTTTTTTTTTTTTTTTTc~~sTTh~~g  g~~^  dqq^TTmqr?  |~}UTTTTTTTTTTTTTTTTTTTk~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~g  g~~^     q~~M     |~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~g  g~~^     q~~M     |~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~ono~~|nnnnnnnnt~~xnnfYYfnnbYYYYYjnnF  VYYnno~~~~~~~~~~~znnnnnu~~~~~~"
"~~~~~~~~~~~}) 8~~y        Y~~k  b~~b  k~~~~~T     y~~8 )}~~~~~~~~~~q     ^~~~~~~"
"~~~~~~~~~~~}) 8~~y        Y~~k  b~~b  k~~~~~T     y~~8 )}~~~~~~~~~~q     ^~~~~~~"
"~~~okk|~~lkk^^^kkg  =^^U  Y~~k  b~~o^^fkkx~~h^^^^^jkk2 'kkkkkkkkkkkh^^^^^l~~~~~~"
"~~~M  y~~8 )}~|     M~~q  Y~~k  b~~~~~^  n~~~~~~~~D                T~~~~~~~~~~~~"
"~~~M  y~~8 )}~|     M~~q  Y~~k  b~~~~~^  n~~~~~~~~D                T~~~~~~~~~~~~"
"~~~M  cggcbbgge  9cbdggfbbdggY  b~~sggdbbv~~~~~lgg;          9cb]  T~~wgggggs~~~"
"~~~M     |~})    D~~u  T~~n     b~~b  k~~~~~~~~M             D~~u  T~~n     b~~~"
"~~~M     |~})    D~~u  T~~n     b~~b  k~~~~~~~~M             D~~u  T~~n     b~~~"
"~~~lgggggcbb% 1gggbbdggfbbdgggggs~~sggv~~~~~~~~lgg;  egg&    9cb]  Ebbdgggggs~~~"
"~~~~~~~~~8    8~~y  M~~q  Y~~~~~~~~~~~~~~~~~~~~~~~D  |~})             Y~~~~~~~~~"
"~~~~~~~~~8    8~~y  M~~q  Y~~~~~~~~~~~~~~~~~~~~~~~D  |~})             Y~~~~~~~~~"
"~~~f^]{~~lkk' .^^Z  =^^bkkg^^^^^^^^^^^^^^^^^^^^^^^6  ]^]$    <kkd     Y~~~~~~~~~"
"~~~M  y~~~~})          T~~n                                  D~~u     Y~~~~~~~~~"
"~~~M  y~~~~})          T~~n                                  D~~u     Y~~~~~~~~~"
"~~~rnn]YY|~~onl  =onnnns~~n     WnnW     annL     jnnnnnnnl  D~~u  LnnhYYYYYm~~~"
"~~~~~~D  |~~~~|  D~~~~~~~~n     b~~b     n~~T     y~~~~~~~|  D~~u  T~~n     b~~~"
"~~~~~~D  |~~~~|  D~~~~~~~~n     b~~b     n~~T     y~~~~~~~|  D~~u  T~~n     b~~~"
"~~~`TT3  STTTTS  D~~xTTTTTL     b~~xqqqqqz~~T  jqrYTT|~}UTWrqoTTO  T~~zqqqqqx~~~"
"~~~M             D~~u           b~~~~~~~~~~~T  u~~D  |~}) 8~~y     T~~~~~~~~~~~~"
"~~~M             D~~u           b~~~~~~~~~~~T  u~~D  |~}) 8~~y     T~~~~~~~~~~~~"
"~~~M  puuuuuuuuuuv~~|uuuuug     ?MMl~~~~~cMM8  u~~vuuQMM# )MMK     T~~~~~oMMi~~~"
"~~~M  y~~~~~~~~~~~~~~~~~~~n        g~~~~~Y     u~~~~~8             T~~~~~k  b~~~"
"~~~M  y~~~~~~~~~~~~~~~~~~~n        g~~~~~Z     u~~~~~8             T~~~~~k  b~~~"
"~~~M  BDC|~}EDJ~~~~~vDDDDD]yyg     g~~cDD5     u~~QDD'             T~~qDD<  b~~~"
"~~~M     |~}) 8~~~~~u     Y~~k     g~~^        u~~D                T~~n     b~~~"
"~~~M     |~}% 6~~~~~u     Y~~k     g~~]        u~~D                T~~n     b~~~"
"~~~||||||~~~|||~~~~~}||||||~~}|||||}~~|||||||||}~~D  y|||||||v     T~~}|||||}~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~D  |~~~~~~~y     T~~~~~~~~~~~~"
"~~~}}}}}}}}}}}}}}}}}}}}}~~~}}}}}}~~}}}}}}}}}~~~~~~D  |~~}}}~~y  #))U~~~}}}}}}~~~"
"~~~N)))))))))))))))))))U~~o)))))c~~c))))))))r~~~~~D  |~}.):~~y  M}}}~~o)))))c~~~"
"~~~M                   T~~n     b~~b        q~~~~~D  |~}) 8~~y  M~~~~~n     b~~~"
"~~~M  688888888888885  T~~n  .88c||a  288-  q~~|||C  |~}:8A~~y  M~~}||l  .88d~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~n  ^~~g     k~~Z  q~~M     |~~~~~~~y  M~~q     ^~~~~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~n  ^~~g     k~~Y  q~~M     |~~~~~~~y  M~~q     ^~~~~~~"
"~~~M  y~~yyyyyyyyy~~u  T~~qDDc~~g  ;DDn~~`DDs~~M     vyyyyyyys  Kyym     ^~~~~~~"
"~~~M  y~~6       C~~u  T~~~~~~~~g  g~~~~~~~~~~~M                         ^~~~~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~g  g~~~~~~~~~~~M                         ^~~~~~~"
"~~~M  y~~8       D~~u  T~~{uuuuu`  `uu{~~~~~xuuI  KMMMMMMMMMMMMMMMMG  ;MMauuy~~~"
"~~~M  y~~8       D~~u  T~~n           k~~~~~T     y~~~~~~~~~~~~~~~~q  Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~n           k~~~~~T     y~~~~~~~~~~~~~~~~q  Y~~k  b~~~"
"~~~M  y~~8       D~~u  T~~sTTTTTG  GTTq~~~~~T  OTTz~~~~~~~~~~~~~|qqkTTf~~qTTk~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~g  g~~~~~~~~T  u~~~~~~~~~~~~~~~~u  T~~~~~~~~~~~~"
"~~~M  y~~8       D~~u  T~~~~~~~~g  g~~~~~~~~T  u~~~~~~~~~~~~~~~~u  T~~~~~~~~~~~~"
"~~~M  y~~]YYYYYYY`~~u  T~~~~~xnnfYYp~~~~~tnn`YYx~~qnn}~~~~}nnnnng  Lnnt~~~~~~~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~~~~k  b~~~~~~~~Y  q~~~~~D  |~~~~|           Y~~~~~~~~~"
"~~~M  y~~~~~~~~~~~~~u  T~~~~~k  b~~~~~~~~Y  q~~~~~D  |~~~~|           Y~~~~~~~~~"
"~~~M  gkkkkkkkkkkkkkd  T~~~~~k  Ukkv~~skkM  akk{~~c^^kkkkkk^^Z  =^^U  Y~~wkku~~~"
"~~~M                   T~~~~~k     g~~^        u~~~~~8    8~~y  M~~q  Y~~k  b~~~"
"~~~M                   T~~~~~k     g~~^        u~~~~~8    8~~y  M~~q  Y~~k  b~~~"
"~~~ibbbbbbbbbbbbbbbbbbbk~~~~~ubbbbbs~~obbbbbbbby~~~~~dbbbbd~~{bbi~~xbbm~~ubbq~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
"";
